### ISSUE TITLE
🐞ANDROID SCREEN FLICKERING ON KEYBOARD CHANGE

### ISSUE THREAD

**Issue by OmarBasem** [wix/react-native-keyboard-input#98] opened 2020-02-07 18:23 UTC
When toggling keyboards, the screen flashes on android. It happens randomly.

**Comment by ggunti** [comment] 2020-04-06 15:50
Also at me. On iOS I was unable to install this package at all. I use RN0.62.

**Comment by M-i-k-e-l** [comment] 2020-05-07 09:02
Hi @OmarBasem,

Thanks for reporting this issue, however it is a duplicate of https://github.com/wix/react-native-keyboard-input/issues/94.
I will close this issue, please add any helpful information you have in that ticket.

**Closed by M-i-k-e-l** 2020-05-07 09:02 UTC
