### ISSUE TITLE
KeyboardAccessoryView offset inconsistent

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#10] opened 2017-04-16 22:50 UTC
Hi Artal!

Repro:
1. Add a background color to the the styles.scrollContainer (e.g. 'red')
2. Load demo app => no offset, red background is visible through the blur view
3. open keyboard => no offset, red background is visible through the blur view
4. close keyboard => offset = height of KeyboardAccessoryView
5. open keyboard  => offset = height of KeyboardAccessoryView
(see screenshots below)

I don't know what the best solution for this is, either

- a) no offset, i.e. the developer would implement an offset via padding, renderFooter.
- b) offset,  i.e. the scrollview is always on top. 

I eventually want to implement a behavior where the offset is always equal to the height of the KeyboardAccessoryView. So for example whenever my textInput box grows to another line, I also want the offset to increase (Similar to WhatsApp or iMessage).  I know how to do this with JS for solution a), but I am not sure how hard it would be if solution b) gets implemented.

Thanks!

![simulator screen shot apr 16 2017 6 27 18 pm](https://cloud.githubusercontent.com/assets/8238976/25074829/4852a14e-22d3-11e7-97ee-645fdfd67ac6.png)

![simulator screen shot apr 16 2017 6 27 44 pm](https://cloud.githubusercontent.com/assets/8238976/25074838/4ece8894-22d3-11e7-9edc-2b0016d356b9.png)

**Comment by artald** [comment] 2017-04-17 00:22
Possibly there's an edge case caused by the "scroll behavior" that's implemented by this package, but I don't see a real issue here.
I'm not sure, but maybe there's a slight confusion here between offset and inset.

You've probably noticed that when the keyboard is shown, you can reach the whole content when you scroll it. That's because it is handled for you on the native side, making sure you're able to see the content in full while allowing it to be visible under the floating bar (blur view), and even beneath the keyboard itself (which has a blur background as well). This is done by setting the proper insets for the scroll-view when necessary. It even handles cases like growing toolbars - if you put some lines in the text input you will see that you can still see the whole content.

On the other hand there's the offset - the point of scrolling inside the content. This is only affected by the "scroll behavior" - a prop we defined to control what happens when the keyboard opens (and only when it opens). It defaults to "fixed offset" which means that it keeps the current scroll position - same offset. Possibly there's an edge case there when the content is not too large and you close the keyboard.
If you wish the offset to remain untouched you can change it by setting the `iOSScrollBehavior` prop:
`iOSScrollBehavior: NativeModulesNativeModules.KeyboardTrackingViewManager.KeyboardTrackingScrollBehaviorNone` - This will make sure the offset is not changed.
The options cover most chat use cases, if not all of them. For example: FB Messenger, WhatsApp, Slack keep the offset ("fixed offset"), iOS messages does "scroll to bottom"

I think we discussed it on a different issue about using an inverted scroll. If/when you do use it, you can utilize the `KeyboardTrackingScrollBehaviorScrollToBottomInvertedOnly` which will auto scroll to bottom when the keyboard show.

Hope I didn't miss anything...
Does it all make sense?

(Note: there was a small issue with the prop type of `iOSScrollBehavior`, now fixed in `v3.0.6`)

**Comment by artald** [comment] 2017-04-17 00:43
Regarding changing the offset when the input grows - you can still do it in JS and it shouldn't have conflicts with either solution.

If you think it's useful, maybe we can consider adding a prop to control this on the native side (what happens to the scroll offset when the `KeyboardAccessoryView` height changes).

**Comment by Thorbenandresen** [comment] 2017-04-17 03:23
Ah ok, thanks a lot for clarifying @artald ! I solved my issue by setting the contentOffset to the height of the KeyboardAccessoryView, thanks for the suggestion.

I also just [tested an inverted ScrollView](https://gist.github.com/Thorbenandresen/e73715dbb00a9a0971ece591c6f27667)  together with the `KeyboardTrackingScrollBehaviorScrollToBottomInvertedOnly` and it works really great! (both scroll to bottom and growing toolbar).  👍 👍 

The only issue I currently have is getting growing toolbar working with the default `KeyboardTrackingScrollBehaviorFixedOffset`. I don't whether this is a new issue or if I simply don't provide the correct props. (demo app)

**Closed** 2017-04-17 03:23 UTC

**Comment by sjmueller** [comment] 2017-04-17 04:51
Hi @artald, really great explanation of the various options for scroll position in relation to keyboard tracking. My question is, can this functionality be used with the new `FlatList` component in react-native? I'm having trouble understanding how the `<KeyboardAccessoryView />` would be able to animate/set the offsets and insets on the `ScrollView` within the `Flatlist`. How are they connected?

**Comment by sjmueller** [comment] 2017-04-17 04:54
To be specific, my intention is to retain the scroll position offset while the inset grows, which would accomplish two things: keep the last items in the list visible as the keyboard opens, rather than those elements getting covered by the keyboard as the viewport shrinks. Also, if the scroll position is somewhere in the middle of the list, then the offset is retained but any items below the viewport are blurred behind the keyboard. Like you said, standard stuff in most messaging apps.

**Comment by artald** [comment] 2017-04-17 10:45
Hi @sjmueller,

The case for `FlatList` is the same as other scroll components with regards to the scrolling insets. At the end, `FlatList` is a wrapper around `VirtualizedList` which renders a `ScrollView`.

This package takes care of the insets on the native side by identifying the scroll container in your screen and applying the insets logic when necessary while taking into account the size of the `KeyboardAccessoryView`.
So the answer is yes - it should take care of the insets even for `FlatList`, but if you're getting different results  - please open an issue.

While the keyboard is open, the correct inset will be applied when the text input grows, but the offset will remain the same.
For the offset behavior that you've mentioned There's a pretty simple JS solution as @Thorbenandresen mentioned. `KeyboardAccessoryView` provides a `onHeightChanged` callback so you can apply any offset change when this happens according to the new height.
If we see that this is a very common use case, I will check if we can solve this on the native side.

**Comment by artald** [comment] 2017-04-17 10:51
@Thorbenandresen great to hear that the inverted solution works well for you! 👍 
And thanks for the gist! I should really at some point make more than one demo screen to showcase the various use-cases (only in our code base we have at least 3 completely different use-cases for this component).

Regarding the growing input issue that you've mentioned: it was never meant to "push" the scroll offsets while growing. You said that you have a JS solution for that... 😃 
It should however in any case take care of the insets while growing so you can scroll and see the whole content.

**Comment by Thorbenandresen** [comment] 2017-04-17 12:01
@artald haha thanks! yes, there is always the the JS solution.  But since I saw the "pushing the scroll offset" working natively with `withKeyboardTrackingScrollBehaviorScrollToBottomInvertedOnly`, I wondered if `KeyboardTrackingScrollBehaviorFixedOffset` can to the same.  :)

**Comment by artald** [comment] 2017-04-17 12:49
@Thorbenandresen hmm.. if pushing the insets work for the inverted scroll style, it wasn't done intentially :) maybe it's just a side effect of the whole inverted scrolling.
Adding this behavior to the fixed scrolling style might be a good idea, thanks! But I do wonder if it needs to be a different opt-in prop (maybe not all users would want this)

**Comment by artald** [comment] 2017-04-24 19:26
@Thorbenandresen @sjmueller 

Latest version (above `3.0.9`) now keeps the insets fixed when the text-input grows and the scroll behavior is set to `KeyboardTrackingScrollBehaviorFixedOffset`.

If you're using it - please let me know if you run into issues. Thanks!
